version: '3.8'

services:
  web:
    build: .
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    environment:
      - GIT_USER=${GIT_USER}
      - GIT_TOKEN=${GIT_TOKEN}
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  git:
    image: alpine/git
    container_name: git_container
    volumes:
      - ./www:/repo
    entrypoint: [ "tail", "-f", "/dev/null" ]

volumes:
  pgdata:
  pgadmin_data:
